# Generated by Django 5.2.6 on 2025-10-04 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('station_name', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('latest_level', models.FloatField(blank=True, null=True)),
                ('latest_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
